### PR TITLE
ENH: modified get_die() for ITkPix wafermap compatibility

### PR DESCRIPTION
**Pull request by mjmucha**
Modified get_die() (added die number mapping) so that the SENTIO prober is compatible with ITkPix wafermap

### CODE REVIEW

**Review by cbespin — CHANGES_REQUESTED** [review]
What is the purpose of mapping here? Shouldn't this be done on the user-side while basil concentrates on the actual device interface and returns column/row information from the machine? @YannickDieter What do you think as a second opinion?

**Comment by cbespin** [comment]
Let's wait for @YannickDieter's opinion on the mapping, as I am not familiar with the probe station and the use case

**Comment by mjmucha** [comment]
I moved now the different die position mappings for the ITk probing sites to a wrapper method inside [bdaq](https://gitlab.cern.ch/silab/bdaq53/-/commit/e13a71569340342d11d3d26bd42d692828500a87).

This PR can now be closed. I will open a new one for the removal of custom mappings/current die position output in basil (SignatoneProber.py and SentioProber.py)

**Comment by cbespin** [comment]
This can be closed in favor of #218, right?

**Pull request closed without merging**
