### PR TITLE
fix current limit gain

### PR DESCRIPTION
**Pull request by thirono**
Since the range of current limit is 0-250mA, the gain should be 0.98.

### CODE REVIEW

**Comment by themperek** [comment]
This is not taken from EEPROM during calibration?

**Comment by thirono** [comment]
The manual of GPAC (GPAC_Short_info_1.1.pdf) said that 
"Programmable current limit: 0..250 mA(common for all channels, can be changed by adjusting resistors values)"
But it is not 0.98, it should be 1.02 (sorry, it was my mistake), should I make another pull request?

**Comment by hansk68** [comment]
The gain is 1. One DAC count equals 1mA. 
Am 04.02.2016 13:31 schrieb thirono <notifications@github.com>:The manual of GPAC (GPAC_Short_info_1.1.pdf) said that 
"Programmable current limit: 0..250 mA(common for all channels, can be changed by adjusting resistors values)"
But it is not 0.98, it should be 1.02 (sorry, it was my mistake), should I make another pull request?

**Comment by themperek** [comment]
@thirono Just update your branch it should take it automatically.

**Comment by themperek** [comment]
Thank you for changing this!

**Pull request merged**
