### PR TITLE
add ext_start

### PR DESCRIPTION
**Pull request by thirono**
add ext_start to spi. the codes were tested on FPGA. The simulation is still
untested.

### CODE REVIEW

**Comment by laborleben** [comment]
I would call it ENABLE_EXTERN (or EN_EXTERN if you like) to match the TDC module.

**Comment by laborleben** [comment]
and the .travis file is missing all our email addresses.

**Comment by themperek** [comment]
EXT_START is used for pulser and SEQ_EXT_START in sequencer should

**Comment by thirono** [comment]
I think I mixed up .travis file. I will fix it tomorrow.

**Comment by thirono** [comment]
thank you

**Comment by themperek** [comment]
This is not the smartest but may work. @laborleben  should disable this version checking somehow here.
Change to:
```python
          mem : {0: 2, 13: 4} # module version for init of spi and mem bytes
```
here:
https://github.com/SiLab-Bonn/basil/blob/development/host/tests/test_StdRegister.py#L20

and all 
```
mem[0] = 1 
```
to 
```
mem[0]=2
```

**Comment by laborleben** [comment]
this is a reminder to also update the unittest ;-)

**Comment by thirono** [comment]
I made a clean new branch

**Pull request closed without merging**
