### PR TITLE
Keithley 2634b

### PR DESCRIPTION
**Pull request by matthias-schuessler**
Adds functionality for the Keithley 2634b Sourcemeter to Basil

### CODE REVIEW

**Comment by YannickDieter** [comment]
Please rebase to check if pipeline is now working.

**Comment by matthias-schuessler** [comment]
Rebase is done - Please merge

**Comment by YannickDieter** [comment]
Thanks, looks good to me.

**Review by YannickDieter — APPROVED** [review]
Thanks!

**Pull request merged**
