### PR TITLE
BUG: fix possible bug in length calculation

### PR DESCRIPTION
**Pull request by laborleben**
ENH: repeat and wait increased to 32bit

### CODE REVIEW

**Comment by themperek** [comment]
Could you update documentation/Readme too.

**Comment by laborleben** [comment]
updated the documentation.

is the change
reg [7:0] status_regs [8+MEM_BYTES*2-1:0];
to 
reg [7:0] status_regs [16-1:0];
breaking anything?

**Comment by themperek** [comment]
Should not. Need to check.

**Comment by themperek** [comment]
Now it is something else. We use spi for StdRegister and now  it does not match anymore.

**Comment by laborleben** [comment]
the module version check fails during init (read:0, require: ==1). Any idea?

**Comment by themperek** [comment]
Make some hack to disable this!

Can remove/change this requirement. Can do some hack like (before init)?
```python
dut['spi']._require_version = ">=0"
dut.init() 
```
Has to also change address now it from 16 not 8 like before.

**Comment by laborleben** [comment]
fixed reading version by adding mem init parameter to Dummy

**Pull request merged**
