### PR TITLE
Flowmeter

### PR DESCRIPTION
**Pull request by AntonioT7**
Improvement on [https://github.com/SiLab-Bonn/basil/blob/development/basil/HL/bronkhorst_elflow.py](url)

### CODE REVIEW

**Comment by leloup314** [comment]
Nice, to link an issue on `basil`, simply put the pound sign and the corresponding issue number e.g. #83

**Comment by AntonioT7** [comment]
#83

**Comment by YannickDieter** [comment]
@matthias-schuessler I guess this is needed for our module qc. Can you please check so that we can merge that too?

**Comment by YannickDieter** [comment]
Closed in favor of #220

**Pull request closed without merging**
