### PR TITLE
ENH: allow sharing of fast trigger with other tdc modules

### PR DESCRIPTION
**Pull request by YannickDieter**
This allows to share the fast sampled trigger signal (in case of `FAST_TRIGGER=1`) with other TDC modules by setting the `BROADCAST` parameter.

### CODE REVIEW

**Comment by YannickDieter** [comment]
Yes sure :)

**Comment by YannickDieter** [comment]
Do we want to have a unit test for the broadcasting, I think it would be nice.
I can test if all tdc module measures the same result when using one common trigger and the same TDc signal.

**Comment by YannickDieter** [comment]
Can we merge?

**Comment by laborleben** [comment]
What is the outcome of the test that you proposed?

**Comment by YannickDieter** [comment]
Ah.. yes. I see, this was the missing part, I forgot. I will add a test.

**Comment by YannickDieter** [comment]
I pushed a test for tdc broadcasting. If you are fine with that you can merge.

**Comment by YannickDieter** [comment]
I pushed a test for tdc broadcasting. If you are fine with that you can merge.

**Comment by YannickDieter** [comment]
I added a test for tdc broadcasting. If you are fine with this you can merge.

**Pull request merged**
